### ISSUE TITLE
PDF with multiple page sizes

### ISSUE THREAD

**Issue by SinaMoetakef** [barteksc/AndroidPdfViewer#373] opened 2017-07-28 19:56 UTC
Is there a way to render a DPF containing pages with different sizes (different aspect ratio) ?
I tried to load a document, it loads fine but the aspect ratio for pages with different sizes is not respected.

**Comment by 1stmetro** [comment] 2017-07-28 21:41
its not been coded.. yet..

**Comment by barteksc** [comment] 2017-08-11 23:02
Duplicate of #213.
This is known issue, currently there is no solution

**Closed by barteksc** 2017-08-11 23:02 UTC
Labels: duplicate
