### ISSUE TITLE
Unable to handle different page orientation & size

### ISSUE THREAD

**Issue by Helmisek** [barteksc/AndroidPdfViewer#359] opened 2017-07-17 17:20 UTC
I am trying to implement a simple pdf file where first page is landscape oriented and the second one is portrait. However it seems that the first page sets the dimension for all others and the portait page is being squeezed to match the width of the first page. How to resolve that? 

Issue preview here:
![issue](https://user-images.githubusercontent.com/6172587/28280738-043c7094-6b25-11e7-8cb1-020bd0645812.png)

**Comment by barteksc** [comment] 2017-07-17 21:24
Duplicate of #213.
This is known issue, currently there is no solution

**Closed** 2017-07-26 06:21 UTC
Labels: duplicate
