### ISSUE TITLE
PDF view rendering problem in android studio 3.0 with library version 2.8.0

### ISSUE THREAD

**Issue by IamOnkar** [barteksc/AndroidPdfViewer#445] opened 2017-11-11 11:22 UTC
Hello,
i am trying to use library , at the time of adding pdf view in xml it shows mi rendering error
it show error on :- com.github.barteksc.pdfviewer.PDFView.computeScroll(PDFView.java:601)

i am adding error detail:-
java.lang.NullPointerException   at com.github.barteksc.pdfviewer.PDFView.computeScroll(PDFView.java:601)   at android.view.View.draw(View.java:18897)   at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4256)   at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)   at android.view.ViewGroup.drawChild(ViewGroup.java:4256)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4042)   at android.view.View.draw(View.java:19024)   at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4256)   at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)   at android.view.ViewGroup.drawChild(ViewGroup.java:4256)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4042)   at android.view.View.draw(View.java:19024)   at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4256)   at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)   at android.view.ViewGroup.drawChild(ViewGroup.java:4256)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4042)   at android.view.View.draw(View.java:19024)   at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4256)   at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)   at android.view.ViewGroup.drawChild(ViewGroup.java:4256)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4042)   at android.view.View.draw(View.java:19159) Copy stack to clipboard

**Comment by barteksc** [comment] 2017-11-11 14:30
Duplicate of #432

**Closed** 2017-11-11 17:15 UTC
Labels: duplicate
