### ISSUE TITLE
Can i get thumbnail bitmap of pages of pdf

### ISSUE THREAD

**Issue by shubhamvishnoi-kiwi** [barteksc/AndroidPdfViewer#49] opened 2016-07-29 07:28 UTC
Hi,

Is there any way for getting thumbnails of pdf using this library. I want to show them in scrollview so that user can jump to a page by tapping on particular thumbnail.

Thanks
Shubham Vishnoi

**Comment by isolpak1** [comment] 2016-08-05 05:51
Any Update?

**Comment by barteksc** [comment] 2016-08-06 14:44
This is duplicate of #20 - you have to use PdfiumAndroid and render thumbnails by yourself.

**Closed by barteksc** 2016-08-06 14:44 UTC
Labels: duplicate

**Comment by isolpak1** [comment] 2016-08-08 07:38
This is not the duplicate...
**I don't want to extract images from pdf**
I want to get the thumbnail of the page (just like WhatsApp)

**Comment by barteksc** [comment] 2016-08-08 08:15
He wanted to get pdf page as bitmap, you want to get pdf page as bitmap, isn't it duplicate? Anyway, use PdfiumAndroid. (I don't use WhatsApp)

**Comment by isolpak1pc** [comment] 2016-08-08 09:37
Issue #20 is basically extracting images from pdf,
**What I want is, Screenshot of pdf page as an image(whether pdf only contains text)**

**Comment by barteksc** [comment] 2016-08-08 09:40
Use PdfiumAndroid

**Comment by isolpak1pc** [comment] 2016-08-08 11:46
I have tried
**PDFBOX** (https://github.com/TomRoush/PdfBox-Android)
**TIKA** (compile 'org.apache.tika:tika-parsers:1.11')
**AndroidPdfViewer** (https://github.com/barteksc/AndroidPdfViewer)

and still unable to find a way to generate image from pdf.

About **PdfiumAndroid** (https://github.com/mshockwave/PdfiumAndroid)
I don't find any helpful link or documentation that helps in performing my required task.

Stackoverflow Question (http://stackoverflow.com/questions/38828396/generate-thumbnail-of-pdf-in-android)

**Comment by barteksc** [comment] 2016-08-08 11:48
https://github.com/barteksc/PdfiumAndroid

**Comment by isolpak1pc** [comment] 2016-08-08 12:26
```
ParcelFileDescriptor fd = null;
fd.open(file, ParcelFileDescriptor.MODE_READ_ONLY);
```

is giving
`java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.FileDescriptor android.os.ParcelFileDescriptor.getFileDescriptor()' on a null object reference`

Can you please help me in this this line
ParcelFileDescriptor fd = ...;

as mentioned here
```
void openPdf() {
    ImageView iv = (ImageView) findViewById(R.id.imageView);
    ParcelFileDescriptor fd = ...;
    int pageNum = 0;
    PdfiumCore pdfiumCore = new PdfiumCore(context);
    try {
```

**Comment by isolpak1pc** [comment] 2016-08-08 12:32
it worked thanks! Great!!! :+1:

**Comment by nafsan1** [comment] 2018-07-02 01:42
im new
https://github.com/barteksc/PdfiumAndroid
why cant run in android studio?

**Comment by vainkatRaman** [comment] 2019-05-08 07:26
> https://github.com/barteksc/PdfiumAndroid

this link not working in android studio. it is not running in studio.
