### ISSUE TITLE
Can not download pdf from remote URI

### ISSUE THREAD

**Issue by lmdic** [barteksc/AndroidPdfViewer#423] opened 2017-10-13 13:40 UTC
My snippet:
```

pdfView = findViewById(R.id.pdfView);
        pdfView.fromUri(Uri.parse("http://dl.dropboxusercontent.com/s/2v42h36tdcd6ii8/portrait.pdf"))
                .defaultPage(currentPage)
                .swipeHorizontal(true).load();
```

But I get error:

```
 E/PDFView ( 8973): load pdf error
 E/PDFView ( 8973): java.io.FileNotFoundException: No content provider: http://dl.dropboxusercontent.com/s/2v42h36tdcd6ii8/portrait.pdf
 E/PDFView ( 8973):	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:758)
 E/PDFView ( 8973):	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:662)
 E/PDFView ( 8973):	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:575)
 E/PDFView ( 8973):	at com.github.barteksc.pdfviewer.source.UriSource.createDocument(UriSource.java:37)
 E/PDFView ( 8973):	at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:53)
 E/PDFView ( 8973):	at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:25)
 E/PDFView ( 8973):	at android.os.AsyncTask$2.call(AsyncTask.java:287)
 E/PDFView ( 8973):	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
 E/PDFView ( 8973):	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
 E/PDFView ( 8973):	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
 E/PDFView ( 8973):	at java.lang.Thread.run(Thread.java:841)

```

Is  method `pdfView.fromUri` not work with remote url?

**Comment by 1stmetro** [comment] 2017-10-15 19:18
I believe you have to download locally, you cannot open from remote server....

**Comment by lmdic** [comment] 2017-10-16 07:02
So I need to download pdf from remote URI by another tool, e.g. Retrofit and view locally by PDFViewer?

**Comment by barteksc** [comment] 2017-10-16 07:21
Exactly

**Comment by barteksc** [comment] 2017-10-16 07:22
Duplicate of #123

**Comment by lmdic** [comment] 2017-10-16 11:48
Maybe it's good to rename method `fromUri` or add comment. Because when I saw it for the first time I thought that this method download pdf from remote URL.

**Comment by barteksc** [comment] 2017-10-16 11:53
It is for Android's URIs, so I think that name is adequate. Information about remote files is in README

**Closed** 2017-10-31 10:04 UTC
Labels: duplicate

**Comment by imBalasankar** [comment] 2018-11-21 13:30
#548

**Comment by TulshiRamDewangan** [comment] 2019-10-09 09:36
**I'm facing the same issue on this project please suggest to me.**

2019-10-09 14:50:21.711 16992-16992/com.github.barteksc.sample E/PDFView: load pdf error
java.io.FileNotFoundException: No content provider: http://nwls.s3.amazonaws.com/temp/pdf/axmoore.pdf
at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1580)
at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1431)
at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1278)
at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1232)
at com.github.barteksc.pdfviewer.source.UriSource.createDocument(UriSource.java:37)
at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:53)
at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:27)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)

**Comment by rahulkushwaha482** [comment] 2021-08-18 11:20
use like this:-
```
package com.pdfpreviewapp;

import android.os.AsyncTask;
import android.os.Bundle;
import android.view.View;
import android.widget.ProgressBar;
import androidx.appcompat.app.AppCompatActivity;
import com.github.barteksc.pdfviewer.PDFView;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;

public class SecondActivity extends AppCompatActivity {
    PDFView pdfView;
    ProgressBar progressCircular;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_second);
        pdfView = findViewById(R.id.pdfView);
        progressCircular = findViewById(R.id.progress_circular);
        progressCircular.setIndeterminate(true);
        new RetrivePDFStream().execute();
    }

    class RetrivePDFStream extends AsyncTask<Void, Void, Void> {

        protected Void doInBackground(Void... voids) {
            try {
                InputStream input = new URL("http://www.africau.edu/images/default/sample.pdf").openStream();
                pdfView.fromStream(input).load();
            } catch (IOException e) {
                e.printStackTrace();
            }
            return null;
        }

        @Override
        protected void onPreExecute() {
            super.onPreExecute();
            progressCircular.setVisibility(View.VISIBLE);
        }

        @Override
        protected void onPostExecute(Void unused) {
            super.onPostExecute(unused);
            progressCircular.setVisibility(View.GONE);
        }
    }
}
```

**Comment by SantoshNayak** [comment] 2023-02-20 10:43
@rahulkushwaha482 Tried your solution, now in pdf screen i have a blank scree, no errors in console

**Comment by rahulkushwaha482** [comment] 2023-02-22 09:03
@SantoshNayak Print all logs in preexecute,post execute, and do in background for better understanding. If not working properly try another way of downloading than assync task . Try volley

**Comment by iamnomandra** [comment] 2023-10-02 09:25
> So I need to download pdf from remote URI by another tool, e.g. Retrofit and view locally by PDFViewer?
> Exactly
@barteksc 
It can possible load  from remote url this library.
