### ISSUE TITLE
APK Size is 20MB , is there a way to reduce this? 

### ISSUE THREAD

**Issue by sillysachin** [barteksc/AndroidPdfViewer#203] opened 2017-02-20 05:27 UTC
We included this library to support viewing of PDF reports in the app. It lead to massive increase in APK size from 4.7Mb to 20.1Mb . 

Is there a way to reduce this size. Can we work on contributing to reduce the size in any manner? Let us know where and what to tinker around to help or solve this.

**Comment by barteksc** [comment] 2017-02-20 07:33
Duplicate of #72

**Closed by barteksc** 2017-02-20 07:33 UTC
Labels: duplicate
