### ISSUE TITLE
Blurred parts of pages

### ISSUE THREAD

**Issue by GothicBezimienny** [barteksc/AndroidPdfViewer#457] opened 2017-11-24 12:53 UTC
Blurred parts of pages when clik prev and next buttom but when i scroll pdf its just fine but, i wanna this buttons to scroll pages one after one if u know what i mean. One click on button set next page on view not half one half next for thsi i need thsi button cna u help there is me code . 

```
protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        getSupportActionBar().setDisplayOptions(ActionBar.DISPLAY_SHOW_CUSTOM);
        getSupportActionBar().setCustomView(R.layout.top_bar);
        downloadButton = findViewById(R.id.download_button);
        showButton = findViewById(R.id.show_button);
        backgroundView = findViewById(R.id.background_image);
        pdfView = findViewById(R.id.pdf_view);

        previousButton = findViewById(R.id.previous_button);
        previousButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (pdfView.getVisibility() == View.VISIBLE && pdfView.getCurrentPage() > 0) {
                    pdfView.jumpTo(pdfView.getCurrentPage() - 1);

                }
            }
        });
        nextButton = findViewById(R.id.next_button);
        nextButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (pdfView.getVisibility() == View.VISIBLE && pdfView.getCurrentPage() < pdfView.getPageCount() - 1) {
                    pdfView.jumpTo(pdfView.getCurrentPage() + 1);

                }
            }
        });

        downloadButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                onDownloadadButtonClick();
            }
        });

        showButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                onReadButtonClick();
            }
        });

        if (currentPage >= 0) {
            pdfView.fitToWidth(currentPage);
        }
    }



 private void createPdf(int pageToShow) {
        String[] perms = {Manifest.permission.WRITE_EXTERNAL_STORAGE};
        if (EasyPermissions.hasPermissions(getApplicationContext(), perms)) {
            String filePath;
            if (Build.VERSION.SDK_INT >= 19) {
                filePath = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS) + "/" +  getString(R.string.app_name) + "/" + fileName;
            } else {
                filePath = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS) + "/" +  getString(R.string.app_name) + "/" + fileName;
            }
            Log.i("FILE", filePath);
            File pdfFile = new File(filePath);
            if (pdfFile.exists()) {
                pdfView.fromFile(pdfFile)
                        .enableSwipe(true) // allows to block changing pages using swipe
                        .swipeHorizontal(true)
                        .enableDoubletap(true)
                        .onPageChange(new OnPageChangeListener() {
                            @Override
                            public void onPageChanged(int page, int pageCount) {
                                currentPage = page;
                            }
                        })
                        .defaultPage(pageToShow)
                        .enableAnnotationRendering(false) // render annotations (such as comments, colors or forms)
                        .password(null)
                        .enableAntialiasing(true) // improve rendering a little bit on low-res screens
                        // spacing between pages in dp. To define spacing color, set view background
                        .spacing(0)
                        .load();
                pdfView.setVisibility(View.VISIBLE);
                backgroundView.setVisibility(View.GONE);
                nextButton.setVisibility(View.VISIBLE);
                previousButton.setVisibility(View.VISIBLE);
            } else {
                showNoFileAlert();
            }
        } else {
            EasyPermissions.requestPermissions(activity, getString(R.string.write_permission), READ_PERM, perms);
        }
    }
```

**Comment by barteksc** [comment] 2017-11-24 13:17
Duplicate of #455

**Comment by GothicBezimienny** [comment] 2017-11-24 13:27
but i dont using second parametr boolean just jumpTo(int) and still got this problem, sometimes blurred part is desipere then its isnt duplicate

**Comment by barteksc** [comment] 2017-11-24 13:43
which version do you use?

**Comment by GothicBezimienny** [comment] 2017-11-24 13:51
2.7  its can be problem ?

**Comment by GothicBezimienny** [comment] 2017-11-24 14:24
ok sorry for this upper version working fine then pls close it

**Closed** 2017-11-25 01:01 UTC
Labels: duplicate
