### ISSUE TITLE
pdfView.fromUri cant work when pdf resources from remote

### ISSUE THREAD

**Issue by JemyZou** [barteksc/AndroidPdfViewer#233] opened 2017-03-15 07:48 UTC
`pdfView.fromUri(Uri.parse("http://10.0.0.39:8080/K1.pdf"))
                .defaultPage(0).enableSwipe(true)
                .onError(new OnErrorListener() {
                    @Override
                    public void onError(Throwable t) {
                        Logger.d(TAG, "onError:"+t.toString());
                    }
                }).onLoad(new OnLoadCompleteListener() {
            @Override
            public void loadComplete(int nbPages) {
                Logger.d(TAG, "loadComplete:");
            }
        }).load();`
when the pdf resources come from remote service，it doesn't work.must i download the pdf to
local?

**Comment by barteksc** [comment] 2017-03-15 08:08
Duplicate of #67

**Closed by barteksc** 2017-03-15 08:08 UTC
Labels: duplicate
