### ISSUE TITLE
Throwing "No Content Provider" Error

### ISSUE THREAD

**Issue by mohdhaider30** [barteksc/AndroidPdfViewer#324] opened 2017-06-18 21:33 UTC
i am using this Uri ->
"https://firebasestorage.googleapis.com/v0/b/sharenotes-9c333.appspot.com/o/Descriptive%20Answer%20Type%20Questions-HVPE%20Unit_1-5%20-%20Dr.pdf?alt=media&token=68411cc7-594c-40d9-acc6-d2a6f51f5854"
Every time i am using your library. Its keep on throwing "No Content Provider" Error. I have used many URIs. But same problem in all of them. Please Help me.

**Comment by barteksc** [comment] 2017-06-18 21:44
Duplicate of #123

**Closed by barteksc** 2017-06-18 21:44 UTC
Labels: duplicate

**Comment by mohdhaider30** [comment] 2017-06-19 08:27
can you share the example uri then? so that i can take reference from it. It would be very helpful.

**Comment by barteksc** [comment] 2017-06-19 09:01
Example uri from Android's MediaStore content provider: content://media/external/images/media/47

**Comment by mohdhaider30** [comment] 2017-06-19 12:03
Thanks man for your help. Now I am manually downloading my pdf from the server and using your library to view it.
