### ISSUE TITLE
java.lang.IllegalStateException: Don't call load on a PDF View without recycling it first

### ISSUE THREAD

**Issue by Maddy14** [barteksc/AndroidPdfViewer#464] opened 2017-12-06 16:09 UTC
I have a tab view wherein three tabs exists. All the tab has pdfview. Each tab loads different pdf file from the database. Whenever the downloaded file loads in the pdfview (all this is happening inside async task) the following error shows up and then the app crashes

`java.lang.IllegalStateException: Don't call load on a PDF View without recycling it first`

I am not sure what am I supposed to do!

```
class MyAsync extends AsyncTask<Void, Void, Void> {

            
           PDFView pdfView;
            

            public MyAsync(PDFView pdfView) {
                
               this.pdfView = pdfView;
                

            }

            @Override
            protected void onPreExecute() {
                super.onPreExecute();
                pd.setMessage("Uploading . . .");
                pd.show();
                pd.setCancelable(false);
            }

            @Override
            protected Void doInBackground(Void... voids) {

               publishProgress();

                return null;
            }

            @Override
            protected void onProgressUpdate(Void... values) {

               


                dataRef.child(dbs).addValueEventListener(new ValueEventListener() {
                    @Override
                    public void onDataChange(DataSnapshot dataSnapshot) {
                        if (dataSnapshot.hasChild(root_child)) {
                            String url = dataSnapshot.child(root_child).getValue().toString();
                            StorageReference island = storage.getReferenceFromUrl(url);

                            final File file;

                            try {
                                file = File.createTempFile(file_name, "pdf");
                                island.getFile(file).addOnSuccessListener(new OnSuccessListener<FileDownloadTask.TaskSnapshot>() {
                                    @Override
                                    public void onSuccess(FileDownloadTask.TaskSnapshot taskSnapshot) {

                                        yes_file(pdfView, tv1, tv2);
                                        pdfView.fromFile(file).load();
                                        
                                    }
                                }).addOnFailureListener(new OnFailureListener() {
                                    @Override
                                    public void onFailure(@NonNull Exception e) {
                                        Toast.makeText(getActivity(), "Upload unsuccessful", Toast.LENGTH_LONG).show();
                                    }
                                });
                            } catch (IOException e) {
                                e.printStackTrace();
                            }


                        } 
                    }

                    @Override
                    public void onCancelled(DatabaseError databaseError) {

                    }
                });
            }

            @Override
            protected void onPostExecute(Void aVoid) {
                super.onPostExecute(aVoid);
                pd.dismiss();
            }
        }
```

**Comment by Maddy14** [comment] 2017-12-07 04:53
I added the line `pdfView.recycle();` before `pdfView.fromFile(file).load(); ` Not sure if this the right way to recycle! Pls help. I Am stuck

**Comment by aayushiGWL** [comment] 2017-12-07 11:40
Same here i am also getting same error and unable to resolve can you please help

**Comment by barteksc** [comment] 2017-12-07 12:00
Is `pdfView.fromFile(file).load()` called in UI thread?

**Comment by aayushiGWL** [comment] 2017-12-07 12:34
mPdfView.fromUri(pdfURI)
        .swipeHorizontal(false)
        .enableDoubletap(true)
        .load();

this is what i have called from main thread


*Aayushi Jain*

Sr. Software Engineer

GoodWorkLabs Services Pvt. Ltd.
*Technology Superstars*

(US) 7100 Stevenson Blvd. Fremont, CA 94538
(INDIA) 4th Floor, Akshay Tech Park, EPIP Zone, Whitefield, Bangalore
 | +91-8904408902 (M)
www.goodworklabs.com | aayushi.jain@goodworklabs.com

**Comment by aayushiGWL** [comment] 2017-12-07 12:39
mPdfView.fromUri(pdfURI)
        .swipeHorizontal(false)
        .enableDoubletap(true)
        .load();

this is what i have called from main thread

**Comment by barteksc** [comment] 2017-12-07 13:10
You are calling `pdfView.fromFile(file).load()` when switching tabs, are this calls executed from main thread?

**Comment by aayushiGWL** [comment] 2017-12-07 13:12
I am Using in Gridview and calling this from my main thread
 mPdfView.fromUri(pdfURI)
.swipeHorizontal(false)
.enableDoubletap(true) 
.load();

**Comment by Maddy14** [comment] 2017-12-07 13:40
yes I Amey calling pdfView.fromFile(file).load() in ui thread @barteksc

**Comment by gustavohansen** [comment] 2017-12-18 20:05
Having the same problem in a RecicleView. When I scroll I have the same problem.
Im executing the next line in the Main Thread: `pdfView.fromBytes(bytes).load();`

**Comment by carbonaro** [comment] 2017-12-28 10:18
Having the same problem

**Comment by MaciejCzekanski** [comment] 2018-01-05 14:07
I can't reproduce it myself, but I have a few crashes because of that error every day. It was fine before I upgraded to v2.8.0. I think the bug was introduced in commit 499ffbc77f5f031d4166c1c544b28aeeb7b7cc94. In load() method there was added PDFView.this.post() call.

@barteksc do you remember why it was added?

**Comment by barteksc** [comment] 2018-01-05 14:20
@MaciejCzekanski 
I cannot reproduce this issue, please show your code.

`.post()` was added to wait for full UI initialization, because sometimes PDF document was loaded faster than  `PDFView` was added to layout and view was empty.

**Comment by MaciejCzekanski** [comment] 2018-01-05 14:36
@barteksc 
PDF file is fetched from backend and when it finishes that code is called from the main thread:

        pdfView.fromFile(pdfFile)
            .spacing(2)
            .onRender({ pages, pageWidth, pageHeight ->
                pdfView?.let {
                    pdfView.isEnabled = true
                    pdfView.fitToWidth()
                    pdfView.setBackgroundColor(ContextCompat.getColor(context, R.color.silver_sand))
                }
            })
            .load()

I think it is somehow possible to call pdfView.load() twice in a way that the second call gets "recycled = false" value.

**Comment by barteksc** [comment] 2018-01-06 16:47
Issue should be fixed in 3.0.0-beta.5 version

**Comment by gustavohansen** [comment] 2018-01-11 17:09
@barteksc when are you planing to release 3.0.0-beta.5 version?

**Comment by barteksc** [comment] 2018-01-11 17:22
It was released few days ago

**Closed** 2018-01-14 01:10 UTC

**Comment by farPlace** [comment] 2019-08-12 02:48
Scroll big pdf,carsh!!!Help.......

**Comment by farPlace** [comment] 2019-08-12 03:07
滚动大pdf，carsh !!!帮助....

**Comment by farPlace** [comment] 2019-08-12 03:08
> 问题应该在3.0.0-beta.5版本中修复

滚动大pdf，carsh !!!帮助...

**Comment by farPlace** [comment] 2019-08-12 03:08
> Issue should be fixed in 3.0.0-beta.5 version

Scroll big pdf,carsh!!!Help.......

**Comment by farPlace** [comment] 2019-08-12 03:09
> Issue should be fixed in 3.0.0-beta.5 version

Scroll big pdf,carsh!!!Help.......

**Comment by farPlace** [comment] 2019-08-12 03:09
> It was released few days ago

Scroll big pdf,carsh!!!Help.......Big crow......

**Comment by kcs-hardikparmar** [comment] 2022-04-21 04:59
I have try with lot's of way. But still this error is there.
Can you please help on this issue.

**Comment by farPlace** [comment] 2022-04-21 05:00
谢谢    祝你天天开心哈

**Comment by farPlace** [comment] 2022-04-21 05:01
Yes，what can i do for you？





发自我的iPhone


------------------ Original ------------------
From: kcs-hardikparmar ***@***.***&gt;
Date: Thu,Apr 21,2022 1:00 PM
To: barteksc/AndroidPdfViewer ***@***.***&gt;
Cc: farPlace ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [barteksc/AndroidPdfViewer] java.lang.IllegalStateException:Don't call load on a PDF View without recycling it first (#464)





 
I have try with lot's of way. But still this error is there.
 Can you please help on this issue.

**Comment by kcs-hardikparmar** [comment] 2022-04-21 05:04
Thank you for your quick ans. 
what i have to do for this issue ?
if there are other lib with same functionally.
Thank you.

**Comment by farPlace** [comment] 2022-04-21 05:08
In order to better understand your problem, please add my wechat account. My wechat account is 851721060



发自我的iPhone


------------------ Original ------------------
From: kcs-hardikparmar ***@***.***&gt;
Date: Thu,Apr 21,2022 1:04 PM
To: barteksc/AndroidPdfViewer ***@***.***&gt;
Cc: farPlace ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [barteksc/AndroidPdfViewer] java.lang.IllegalStateException:Don't call load on a PDF View without recycling it first (#464)





 
Thank you for your quick ans.
 what i have to do for this issue ?
 if there are other lib with same functionally.
 Thank you.

**Comment by kcs-hardikparmar** [comment] 2022-04-21 05:13
Sorry, I haven't wechat.

**Comment by farPlace** [comment] 2022-04-21 05:14
Do you have any popular social software in China?



发自我的iPhone


------------------ Original ------------------
From: kcs-hardikparmar ***@***.***&gt;
Date: Thu,Apr 21,2022 1:13 PM
To: barteksc/AndroidPdfViewer ***@***.***&gt;
Cc: farPlace ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [barteksc/AndroidPdfViewer] java.lang.IllegalStateException:Don't call load on a PDF View without recycling it first (#464)





 
Sorry, I haven't wechat.
